# This file is generated by setup.py. DO NOT EDIT!

git_version = "b05c24911b5b66dc2b9741619ea979e77bd00f76"
mlu_version = "1.33.1+torch2.11.0"
cntoolkit_version = "4.7.1"
pytorch_git_version = "70d99e998b4955e0049d13a98d77ae1b14db1f45"
compiled_with_cxx11_abi = True
built_with_clang = False
