# Be extra careful when you edit this file, because it affects AOTInductor ABI compatibility. See
# https://github.com/pytorch/pytorch/blob/7e86a7c0155295539996e0cf422883571126073e/torchgen/gen.py#L2424-L2436
# for details.
#
# The inductor_fallback_ops list is based on the fallback ops from torch/_inductor/lowering.py.
# Generally speaking, it is ok to add a new op to the list, but you need to run
# `python torchgen/gen.py --update-aoti-c-shim` in order to regenerate C shim header files.
# But it is NOT ok to remove an existing fallback op from the list, since that will break
# some existing AOTInductor-compiled models.
inductor_fallback_ops = {
    "aten.abs.default": {},
    "aten._adaptive_avg_pool2d_backward.default": {},
    "aten._adaptive_avg_pool2d.default": {},
    "aten.add.Tensor": {},
    "aten.adaptive_max_pool2d_backward.default": {},
    "aten.adaptive_max_pool2d.default": {},
    "aten.addbmm.default": {},
    "aten._addmm_activation.default": {},
    "aten.addmm.out": {},
    "aten.addmv.default": {},
    "aten.angle.default": {},
    "aten.arange.default": {},
    "aten.avg_pool2d_backward.default": {},
    "aten.avg_pool2d.default": {},
    "aten.avg_pool3d_backward.default": {},
    "aten.avg_pool3d.default": {},
    "aten.bernoulli_.float": {},
    "aten.bernoulli_.Tensor": {},
    "aten.bmm.out": {},
    "aten.baddbmm.out": {},
    "aten.baddbmm.default": {},
    "aten.cat.default": {},
    "aten.cat": {},
    "aten._cdist_backward.default": {},
    "aten._cdist_forward.default": {},
    "aten.cholesky_solve.default": {},
    "aten.clone.default": {},
    "aten._cudnn_rnn.default": {},
    "aten._cudnn_rnn_backward.default": {},
    "aten.concat.default": {},
    "aten.convolution.default": {},
    "aten.convolution_backward.default": {},
    "aten.constant_pad_nd.default": {},
    "aten.cummax.default": {},
    "aten.cummin.default": {},
    "aten.cumprod.default": {},
    "aten.cumsum.default": {},
    "aten._efficientzerotensor.default": {},
    "aten._embedding_bag.default": {},
    "aten.embedding.default": {},
    "aten.expand.default": {},
    "aten.exponential.default": {},
    "aten._fft_c2c.default": {},
    "aten._fft_r2c.default": {},
    "aten.gather.default": {},
    "aten.gather.out": {},
    "aten.gelu.default": {},
    "aten.grid_sampler_2d_backward.default": {},
    "aten.hann_window.default":{},
    "aten.histc.default": {},
    "aten.histogram.bin_ct": {},
    "aten._histogramdd_bin_edges.default": {},
    "aten._histogramdd_from_bin_cts.default": {},
    "aten.index.Tensor": {},
    "aten._log_softmax.default": {},
    "aten.kthvalue.default": {},
    "aten.logcumsumexp.default": {},
    "aten.masked_select.default": {},
    "aten.masked_scatter.default": {},
    "aten.masked_scatter_backward.default": {},
    "aten.max_pool2d_with_indices_backward.default": {},
    "aten.max_pool2d_with_indices.default": {},
    "aten.max.default": {},
    "aten.max.dim": {},
    "aten.mean.dim": {},
    "aten.median.default": {},
    "aten.mm.out": {},
    "aten.mul.Scalar": {},
    "aten.mul.Tensor": {},
    "aten.native_batch_norm.default": {},
    "aten.native_dropout.default": {},
    "aten.native_layer_norm.default": {},
    "aten.native_layer_norm_backward.default": {},
    "aten.normal_functional.default": {},
    "aten.nonzero.default": {},
    "aten.polar.default": {},
    "aten.pow.Scalar": {},
    "aten.pow.Tensor_Scalar": {},
    "aten.pow.Tensor_Tensor": {},
    "aten.rand.default": {},
    "aten.rand.generator": {},
    "aten.randint.default": {},
    "aten.randint.generator": {},
    "aten.randint.low": {},
    "aten.randint.low_out": {},
    "aten.randn.default": {},
    "aten.randn.generator": {},
    "aten.randperm.default": {},
    "aten.repeat.default": {},
    "aten.repeat_interleave.Tensor": {},
    "aten.replication_pad1d_backward.default": {},
    "aten.replication_pad2d_backward.default": {},
    "aten.reshape.default": {},
    "aten.resize_.default": {},
    "aten.resize_as_.default": {},
    "aten._safe_softmax.default": {},
    "aten._scaled_mm.default": {},
    "aten._scaled_dot_product_fused_attention_overrideable.default": {},
    "aten.scatter_reduce.two": {},
    "aten.scatter_reduce.two_out": {},
    "aten.scatter.src": {},
    "aten.scatter.src_out": {},
    "aten.scatter.value_out": {},
    "aten.searchsorted.default": {},
    "aten.slice.Tensor": {},
    "aten.soft_margin_loss_backward.default": {},
    "aten._softmax.default": {},
    "aten.sort.default": {},
    "aten.sort.stable": {},
    "aten.split.Tensor": {},
    "aten.squeeze.dim":{},
    "aten.sum.dim_IntList": {},
    "aten.sum.default": {},
    "aten._sparse_coo_tensor_with_dims_and_tensors.default": {},
    "aten._thnn_fused_lstm_cell.default": {},
    "aten.topk.default": {},
    "aten._trilinear.default": {},
    "aten.where.self": {},
    "aten.unfold.default":{},
    "aten.uniform.default": {},
    "aten.unsqueeze.default": {},
    "aten._unique2.default": {},
    "aten._unsafe_index.Tensor":{},
    "aten._unsafe_view.default": {},
    "aten.upsample_bicubic2d_backward.default": {},
    "aten.upsample_linear1d_backward.default": {},
    "aten.upsample_trilinear3d_backward.default": {},
    "aten.var.correction": {},
    "aten.view.default": {},
    "aten.view_as_complex.default": {},
    "aten.view_as_real.default": {},
    "aten.view.dtype": {},
    "aten.zeros.names": {},
    "torch_mlu.grouped_gemm.default": {},
    "torch_mlu.fused_mm.default": {},
    "torch_mlu.fused_bmm.default": {},
    "torch_mlu.fused_convolution.default": {},
}
